# TODO: which frame?
# Car state related # w.r.t. Car frame, for now
float64 	X 			# X position, [m]
float64 	Y 			# Y position, [m]
float64 	yaw 		# yaw angle, [rad]
float64     steering 	# steering angle, [rad]

# Car related
float64 	length_wheelbase 	# length of wheelbase, [m]
float64 	length_outer_wheel_distance # length of outer wheel distance, [m]
float64     length_inner_wheel_distance # length of inner wheel distance, [m]

# Access point (middle of the front edge of front wheels)
float64     aX          # X position, [m]
float64     aY          # Y position, [m]
float64     aYaw        # yaw angle, [rad]